version: '3.1'

services:
  wordpress:
    build: 
      context: ./
    restart: always
    container_name: WordPress
    links:
      - db
      - mailhog
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    command: 
      - "--innodb_use_native_aio=0"
      - "--innodb_buffer_pool_size=10M"
      - "--innodb_log_file_size=100M"
    volumes:
      - ./db:/var/lib/mysql
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    links: 
        - db